batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202404151017
train_epochs: 1000
train_workers: 20
vocab: 0Pv2FQ1BZp&Y5'kD*uT(b-9#+fHm:Rl!in/AEI;)MKWtq7Vrz?N.JL3xOUa"6eygocCXs4Sd8,Gjhw
width: 128
